### ISSUE TITLE
Error pythonPath when starting RStudio

### ISSUE THREAD

**Issue by AdelineJerome** [rostools/r-cubed-intermediate#14]
I had an error message when starting RStudio:
`Error in file.exists(pythonPath) : 
  file name conversion problem -- name too long?`
It was not a problem at first. After a few months of using RStudio, it started to crash when I restart my R session. I fixed the error following this:
https://stackoverflow.com/questions/74894455/what-does-error-in-file-existspythonpath-file-name-conversion-problem-na

Now, it works again.

**Comment by lwjohnst86** [comment]
Thanks for this! I've added this to the FAQ in the guides website 😁 https://guides.rostools.org/faq
