### ISSUE TITLE
R formula in MacOS has various issues with development tools

### ISSUE THREAD

**Issue by AndersAskeland** [rostools/r-cubed-intermediate#29]
The suggested way of installing R on MacOS can result in various when building packages from source. Consider changing to R cask ´brew install homebrew/cask/r`.

Don't know if anyone else have issues with this.

**Comment by AndersAskeland** [comment]
I believe the reason for this is that the Cask version comes with tried and true developer tools, while the formula add these using brew, and is hence reliant on brew having correct configurations.

**Comment by lwjohnst86** [comment]
What's the difference between that and `brew install --cask r`?

**Comment by AndersAskeland** [comment]
`brew install --cask r` and  `brew install home-brew/cask/r` is identical.

**Comment by lwjohnst86** [comment]
fixed in r3admin
