### ISSUE TITLE
Move downloading and processing of zipped dataset into r3/r3admin and have them download the zip file from there

### ISSUE THREAD

**Issue by lwjohnst86** [rostools/r-cubed-intermediate#34]
We consistently have too many issues with this dataset and the unzipping. So instead, move it into the r3 or r3admin package and have them download it from there.

**Comment by AndersAskeland** [comment]
Good idea!

**Comment by lwjohnst86** [comment]
I think with including a `dir_delete()` at the top of the `mmash.R` script, this will solve this issue, so closing for now.
