### ISSUE TITLE
Links to external websites with the same content as further down in the post

### ISSUE THREAD

**Issue by signekb** [rostools/r-cubed-intermediate#38]
Isn't the material linked to here: 
https://github.com/rostools/r-cubed-intermediate/blob/952dabe9b15caebe40361e48ac3f4e93ddabf11b/preamble/pre-course.qmd#L30-L38

the same as in `3.3` and `3.4` on the site?
https://github.com/rostools/r-cubed-intermediate/blob/952dabe9b15caebe40361e48ac3f4e93ddabf11b/preamble/pre-course.qmd#L78-L95

**Comment by lwjohnst86** [comment]
ugh, thanks for that catch, I should have read it more thoroughly before sending it to the participants 😒
