### ISSUE TITLE
Suggestion: Highlight new files in the file tree at the end of the course?

### ISSUE THREAD

**Issue by signekb** [rostools/r-cubed-intermediate#43]
To make it easer to see which files have been added from the beginning to the end of the course, can the new files be highlighted somehow? 

https://github.com/rostools/r-cubed-intermediate/blob/30eeb5fe007a017f5ca4d78721d6f8c90e4d91ae/sessions/introduction.qmd#L82-L108

**Comment by lwjohnst86** [comment]
Unfortunately there isn't highlighting available within code chunks (not yet anyway), but I have another idea for it.
