### ISSUE TITLE
Read data with mmash.R cannot remove old data

### ISSUE THREAD

**Issue by AndersAskeland** [rostools/r-cubed-intermediate#48]
This causes a issue if running mmash.R several times

2nd iteration it will place the DataPaper folder inside mmash folder. Third time will give an error.

Potential fix would be to delete the mmash folder before moving the new one.

**Comment by AndersAskeland** [comment]
Is commented out in section 8.9 so will usually not be relevant. However, one could still add a line to remove the old data if wanted.

**Comment by lwjohnst86** [comment]
Ooo, that's a nice idea for a fix, with deleting the mmash folder!
